Allow sending to scripts from payto and paytomany RPCs
spesmilo/electrum pull request #7203
Opened 2021-04-12 23:02 UTC by metalicjames

This PR:

- Refactors `parse_script`, `parse_address` and `parse_output` from the `gui` module into `bitcoin`
- Allows `payto` to accept scripts just like the GUI
- Allows `paytomany` to accept scripts like the GUI

The use-case of this PR is for creating OP_RETURN outputs from the command line.

Before this change:
```
electrum --testnet payto -F tb1q2s7kk7qp0urvz46wpjg2jgp7vfxhj7gy63p2sh -c tb1q2s7kk7qp0urvz46wpjg2jgp7vfxhj7gy63p2sh "OP_RETURN 94cab8cbeb53d63dba67e015450eb83c0682b5aa2d232fbb06ddf260d64a65b1" 0
invalid bitcoin address: OP_RETURN 94cab8cbeb53d63dba67e015450eb83c0682b5aa2d232fbb06ddf260d64a65b1
``` 

After:
```
electrum --testnet payto -F tb1q2s7kk7qp0urvz46wpjg2jgp7vfxhj7gy63p2sh -c tb1q2s7kk7qp0urvz46wpjg2jgp7vfxhj7gy63p2sh "OP_RETURN 94cab8cbeb53d63dba67e015450eb83c0682b5aa2d232fbb06ddf260d64a65b1" 0
02000000000101d7e6deda8ad91c1fe7ab3d0cff3d2d95b0e9efc3b774a74d995ff69736f547f80100000000fdffffff020000000000000000226a2094cab8cbeb53d63dba67e015450eb83c0682b5aa2d232fbb06ddf260d64a65b18641100000000000160014543d6b78017f06c1574e0c90a9203e624d79790402473044022002d20f5298dfa29fd106903c62b93138dcada10745547d45edbcd6922f52cea602204f69dd8bba9908821fa8004fd1c758122aada6643b1753527e6eed89e0c695460121022dab9a6611baa4d42d2ec0cc8741c1f369f8265b1eeaedcbd971533885d9eebf28141e00
```

2021-04-15 14:59 UTC, SomberNight requested changes
I think we can expose the script-parsing to the payto CLI command, but please do not expose the openalias-parsing.

2021-04-15 14:59 UTC, SomberNight commented on electrum/bitcoin.py
> +    m = re.match('^'+RE_ALIAS+'$', r)
`RE_ALIAS` is not defined here.
(but see other comment first: don't move `parse_address` to bitcoin.py at all)

2021-04-15 14:59 UTC, SomberNight commented on electrum/bitcoin.py
> +        pass
I would strongly prefer not exposing the openalias regex stuff to the CLI, and would keep that in the Qt GUI.
First, I suggest doing this here instead:

```suggestion
    if is_address(x):
        return return bfh(address_to_script(address))
```

Second, let's keep `parse_address` in the GUI code where it was.
Then, to maintain the current behaviour for the GUI code, also keep a method `parse_output` in the GUI, which first calls `parse_address` and then falls back to this methiod here (`bitcoin.parse_output`).

2021-04-22 15:18 UTC, SomberNight requested changes
I've added a unit test in https://github.com/spesmilo/electrum/commit/af44c846cc53d31c32a25826af596340053448e7 that tests using the `payto` command to pay a bitcoin address. This PR would currently make that test fail. Please fix that, otherwise it looks ok.
It would also be nice if you could add a similar test that pays to an OP_RETURN output or some other script that uses the new functionality.

2021-04-22 15:18 UTC, SomberNight commented on electrum/bitcoin.py
> +        return bfh(address_to_script(address))
`address` is not defined.

2026-06-11 11:37 UTC, accumulator commented
stale

2026-06-11 11:37 UTC, closed without merging