wallet: RBF batch payments manager
spesmilo/electrum pull request #9298
Opened 2024-11-12 09:29 UTC by ecdsa

2025-01-06 15:58 UTC, SomberNight reviewed
some preliminary comments

2025-01-06 15:58 UTC, SomberNight commented on electrum/txengine.py
> +            BIP69_sort=False,
why disable bip69 sort?

2025-01-06 15:58 UTC, SomberNight commented on tests/test_sswaps.py
> -    def test_claim_tx_for_successful_reverse_swap(self):
Why delete these tests?
Just because `SwapManager._create_and_sign_claim_tx` is being removed?

The tests could be adapted to test `create_claim_txin` instead. Maybe feed the txin to `wallet.create_transaction` along with some hardcoded values.
The point is to test that the txin is constructed correctly, but the easiest way of doing that is comparing a full tx.

2025-01-07 08:25 UTC, ecdsa commented on electrum/submarine_swaps.py
> +        txin.privkey = swap.privkey
see `sign_transaction` in `wallet.py`

2025-01-07 08:28 UTC, ecdsa commented on electrum/txengine.py
> +            BIP69_sort=False,
when sweeping htlc outputs with sighash single-anyonecanpay, the order must be preserved.

2025-01-07 12:09 UTC, ecdsa commented on tests/test_sswaps.py
> -    def test_claim_tx_for_successful_reverse_swap(self):
> The point is to test that the txin is constructed correctly, but the easiest way of doing that is comparing a full tx.

Creating a full tx in order to check the construction of a tx input is indeed the easiest way, but it is completely overkill. 
I think we should try to put a little bit more efforts in writing tests.

2025-01-10 09:57 UTC, ecdsa commented on electrum/txengine.py
> +class TxEngine(Logger):
ok let's call it TxBatcher

2025-01-26 06:45 UTC, ALANthemoor commented on tests/test_sswaps.py
> -    def test_claim_tx_for_successful_reverse_swap(self):
RELEASE-NOTES

2025-02-12 09:34 UTC, ecdsa commented on electrum/txengine.py
> +            BIP69_sort=False,
note that regtests would be failing if this was set to True

2025-02-12 09:48 UTC, ALANthemoor commented on electrum/txengine.py
> +            BIP69_sort=False,
What happened 😔

2025-02-15 09:32 UTC, ecdsa commented on tests/test_sswaps.py
> -    def test_claim_tx_for_successful_reverse_swap(self):
sweeping from swaps is now tested in test_txbatcher.py

2025-02-19 09:38 UTC, f321x commented
I get this exception and electrum crashes when batching is enabled and trying to fully spend an unconfirmed utxo from the "Coins" tab with right click -> fully spend -> send to address in clipboard.
```
Traceback (most recent call last):
  File "/home/user/code/electrum-fork/electrum/gui/qt/confirm_tx_dialog.py", line 116, in timer_actions
    self.update()
    ~~~~~~~~~~~^^
  File "/home/user/code/electrum-fork/electrum/gui/qt/confirm_tx_dialog.py", line 120, in update
    self.update_tx()
    ~~~~~~~~~~~~~~^^
  File "/home/user/code/electrum-fork/electrum/gui/qt/confirm_tx_dialog.py", line 641, in update_tx
    self.tx = self.make_tx(fee_estimator, confirmed_only=confirmed_only)
              ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/code/electrum-fork/electrum/gui/qt/send_tab.py", line 320, in <lambda>
    make_tx = lambda fee_est, *, confirmed_only=False: self.wallet.make_unsigned_transaction(
                                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        coins=get_coins(nonlocal_only=nonlocal_only, confirmed_only=confirmed_only),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        outputs=outputs,
        ^^^^^^^^^^^^^^^^
        fee=fee_est,
        ^^^^^^^^^^^^
        is_sweep=is_sweep)
        ^^^^^^^^^^^^^^^^^^
  File "/home/user/code/electrum-fork/electrum/util.py", line 492, in do_profile
    o = func(*args, **kw_args)
  File "/home/user/code/electrum-fork/electrum/wallet.py", line 1879, in make_unsigned_transaction
    base_tx = self.get_unconfirmed_base_tx_for_batching(outputs, coins)
  File "/home/user/code/electrum-fork/electrum/wallet.py", line 1774, in get_unconfirmed_base_tx_for_batching
    output_amount = sum(o.value for o in outputs)
TypeError: unsupported operand type(s) for +: 'int' and 'str'
```

2025-02-21 10:21 UTC, ecdsa commented
>   File "/home/user/code/electrum-fork/electrum/wallet.py", line 1879, in make_unsigned_transaction
>     base_tx = self.get_unconfirmed_base_tx_for_batching(outputs, coins)

This does not correspond to the code in the `batch_payment_manager` branch.
`get_unconfirmed_base_tx_for_batching` is not used anymore (and should probably be removed)

2025-02-21 14:37 UTC, SomberNight commented on electrum/txbatcher.py
> +        self.batch_payments.append(output)
Is this class supposed to be thread-safe?
Calling this from GUI and asyncio thread at the "same time" might result in some hard-to-debug issues atm.

2025-02-23 08:35 UTC, ecdsa commented on electrum/txbatcher.py
> +        self.batch_payments.append(output)
thanks, I added a lock

2025-02-24 11:03 UTC, ecdsa commented
Note: This PR does not work well with fee settings.

When we change the fee settings in `ConfirmTxDialog`, this side effects the fee settings in `config`, which is in turn used by `TxBatcher`. I think we should use a `FeeEstimator` object that holds fee settings and provides fee estimates, without committing the settings to config.

2025-02-25 17:43 UTC, SomberNight requested changes

2025-02-25 17:43 UTC, SomberNight commented on electrum/txbatcher.py
> +        self.batch_payments = self._to_pay_after(tx)
does this not need the lock?
```suggestion
        with self.lock:
            self.batch_payments = self._to_pay_after(tx)
```

2025-02-25 17:43 UTC, SomberNight commented on electrum/txbatcher.py
> +        self.batch_inputs = self._to_sweep_after(tx)
should we not take the lock everywhere `self.batch_inputs` is iterated on, mutated, or reassigned?
Well, maybe that's too aggressive but note that just because it is a dict, that does not suddenly solve all thread-safety.

Anyway, as-is, I think if another thread calls `add_sweep_info` while `_to_sweep_after` is being executed, we might lose the side-effect of `add_sweep_info`.

2025-02-25 17:43 UTC, SomberNight commented on electrum/txbatcher.py
> +        self._base_tx = None           # current batch tx. last element of batch_txids
TxBatcher needs to be taught the 100 KB max tx size standardness rule. It must not try creating txs that are too large.

2025-02-25 17:43 UTC, SomberNight commented on electrum/lnwatcher.py
> +        self.lnworker.wallet.txbatcher.add_sweep_info(sweep_info)
In general it is not safe to batch all lightning sweeps together, due to (1) pinning attacks and (2) split views of mempools due to distributed nature of network.

---

Perhaps the scariest problem is to do with revocations:
- counterparty force-closes using old state
- ctx has some htlcs
- counterparty creates a 2nd stage htlc tx ("tx1"), that spends one or more of the ctx's htlc outputs, and they add a lot of inputs/outputs to this tx (which they can do when using anchor channels due to sighash_single). They ensure tx1 is large (in vbytes), pays a low feerate so it does not confirm, but it pays a high absolute fee (as it is large).
- the local client then tries to punish the counterparty: we want to sweep `tx1:0` (the first output) but we also want to sweep `to_local`
- if we batch the sweeping of those two utxos, to create "tx2", as "tx1" might ~never confirm, "tx2" won't get mined either.
- and in the meantime, the relative timelock (to_self_delay_ on `to_local` is ticking. If that expires, the remote can just sweep it for themselves.

(see https://github.com/lightning/bolts/pull/803)

The easiest workaround I believe would be to avoid batching all revocations. That is, any sweep where we use the revocation path, should be a completely separate 1-in-1-out tx.

---

However, it's not just about revocations. In general, I believe it is not safe to batch the sweeping of txos where some txos are spendable by both us and the remote, and some only by us. Perhaps we should have a separate "safe" batch for sweeping txos that are only spendable by us, and another for the risky txos.

One complication is that some utxos transition from "only spendable by us" to "spendable by either party" over time (~already when a timelock gets close to expiry, but especially after it expires).

I am not yet sure exactly how to handle this.

---

Also, btw, to simplify reasoning, I think we should consider strictly separating the batching of user-initiated txs (e.g. simple sends), and lnwatcher/swap_manager stuff.

2025-02-26 10:59 UTC, ecdsa commented on electrum/txbatcher.py
> +        self.batch_payments = self._to_pay_after(tx)
done

2025-02-26 11:00 UTC, ecdsa commented on electrum/txbatcher.py
> +        self.batch_inputs = self._to_sweep_after(tx)
indeed. I made the locking more aggressive.

2025-02-27 18:32 UTC, SomberNight commented on electrum/lnwatcher.py
> +        self.lnworker.wallet.txbatcher.add_sweep_info(sweep_info)
> (2) split views of mempools due to distributed nature of network

Example:
- at block 0, remote counterparty force-closes small-value chan1, the to_self_delay is 1000
- we are offline
- at block 1000, remote force-closes high-value chan2, the to_self_delay is 1000
- at block 1100, we come online - and the remote somehow learns of this instantly
  - they try to partition the mempool
  - "at the same time":
    - remote broadcasts tx1, that sweeps the to_local output of their chan1
      - they try to pin this tx to the mempool: it is large in size, low feerate, but highish absolute fee
    - we broadcast tx2, that sweeps both to_locals (from chan1 and chan2) in a single batched tx
- if the remote is successful, the mempool is now partitioned so that most nodes and miners have tx1, but our electrum server has tx2
  - the attacker's goal here is that neither tx1 nor tx2 gets mined
- now the attacker waits.
- at block 2000, the CSV for "high-value" chan2 has expired, and the remote broadcasts a 1-in-1-out tx that spends just that to_local

2025-03-11 13:29 UTC, ecdsa commented on electrum/lnwatcher.py
> +        self.lnworker.wallet.txbatcher.add_sweep_info(sweep_info)
ok, I believe this is addressed:
 - `TxBatcher` now uses separated TXBatche instances for swaps and lnwatcher.
 - `SweepInfo` has a `can_be_batched` boolean field, which is set only for inputs that only us can spend. If it is not set, a TxBatch instance is created for sweeping only that input.
 - Notably, second-stage htlc transactions are not batched. (we might want to batch them in some cases, but this is left for future work)

2025-03-11 16:02 UTC, SomberNight commented on electrum/wallet.py
> +        )
no outputs and zero fee? what is this supposed to do?
and in any case, maybe we should make make_unsigned_transaction enforce there is at least one output (that's a consensus rule btw)

2025-03-11 17:28 UTC, ecdsa commented on electrum/wallet.py
> +        )
Given no outputs, `make_unsigned_transaction` will send all the coins to a change address.
Zero fee: this is a future transaction, its purpose is only to provide feedback to the user. 
A fee will be added when the actual tx is broadcast.

2025-03-11 18:01 UTC, SomberNight commented on electrum/wallet.py
> +        )
> Given no outputs, make_unsigned_transaction will send all the coins to a change address.

Ah right... ok, makes sense. Could you add a comment "this will send all the coins to a change address"?

Note that `create_transaction` tries to sign this by default. Is that intentional in this case? (with zero fee?)
(indeed we should just kill `wallet.create_transaction`)

2025-03-13 09:09 UTC, ecdsa commented on electrum/wallet.py
> +        )
indeed, it is better not to sign. I passed `sign=False`
(the future tx used to have a fee, and to be signed so that the user can broadcast early)

2025-03-13 09:13 UTC, ALANthemoor commented on electrum/wallet.py
> +        )
![Screenshot_20250206-123829](https://github.com/user-attachments/assets/e6f67a8f-c8f1-4d66-94a2-522eecf2952c)

2025-03-13 09:47 UTC, merged